Fixed Type Annotation issue #9 in #opentrack-Metriks-9 
intuit/metriks pull request #15
Opened 2020-10-01 23:16 UTC by AnshumaJain

Contributed by vGHC 2020 Attendees, Here are their respective GitHub accounts with name:  - 
- Jyotsna Priya: https://github.com/jyotsna-priya 
- Deepthi Kailash: https://github.com/deepthikailash 
- Menna Khaliel: https://github.com/Menna13   
- Anshuma Jain: https://github.com/AnshumaJain 

2020-10-02 00:23 UTC, wontonswaggie requested changes

2020-10-02 00:23 UTC, wontonswaggie commented on metriks/ranking.py
> +def recall_at_k(y_true: np.ndarray, y_prob: np.ndarray, k: int) -> float:
The return should actually be `np.ndarray` as well. A `float` would be a single value.

2020-10-02 00:23 UTC, wontonswaggie commented on metriks/ranking.py
> +def precision_at_k(y_true: np.ndarray, y_prob: np.ndarray, k: int) -> float:
Same here. This should be `np.ndarray`.

2020-10-02 00:23 UTC, wontonswaggie commented on setup.py
> +        'numpy', 'pytypes'
Please add `pytypes` in the next line.

2020-10-02 00:23 UTC, wontonswaggie commented on tests/test_confusion_matrix_at_k.py
> +    print(type(result))
Please remove this print statement. Perhaps an assertion test can be made for this instead of print statement.

2020-10-02 00:23 UTC, wontonswaggie commented on tests/test_confusion_matrix_at_k.py
> +    print(type(result[0]))
Please remove this print statement. Perhaps an assertion test can be made for this instead of print statement.

2020-10-02 00:23 UTC, wontonswaggie commented on tests/test_mean_reciprocal_rank.py
> +    print(type(result))
Please remove this print statement. Perhaps an assertion test can be made for this instead of print statement.

2020-10-02 04:43 UTC, rdedhia requested changes

2020-10-02 04:43 UTC, rdedhia commented on metriks/ranking.py
> +from typing import Tuple
Could you use `isort` to order the imports? Generally, imports should be organized in three groups, with a newline between each group of imports:
1. Standard library imports.
2. Related third party imports.
3. Local application/library specific imports.

Reference: https://www.python.org/dev/peps/pep-0008/#imports

2020-10-03 06:00 UTC, AnshumaJain reviewed
Made the necessary changes and resubmitted the PR.

2020-10-03 06:00 UTC, AnshumaJain commented on metriks/ranking.py
> +from typing import Tuple
that's good to know! will make this change.

2020-10-03 06:00 UTC, AnshumaJain commented on setup.py
> +        'numpy', 'pytypes'
will do

2020-10-03 06:00 UTC, AnshumaJain commented on tests/test_confusion_matrix_at_k.py
> +    print(type(result))
Thanks for letting me know, will fix this.

2020-10-03 06:00 UTC, AnshumaJain commented on tests/test_confusion_matrix_at_k.py
> +    print(type(result[0]))
Thanks for letting me know, will fix this.

2020-10-03 06:00 UTC, AnshumaJain commented on tests/test_mean_reciprocal_rank.py
> +    print(type(result))
Thanks for letting me know, will fix this.

2020-10-03 06:00 UTC, AnshumaJain commented on metriks/ranking.py
> +def recall_at_k(y_true: np.ndarray, y_prob: np.ndarray, k: int) -> float:
I did try np.ndarray but it is throwing error, because the function is returning float output. See example below-

Example:
    >>> y_true = np.array([
        [0, 0, 1],
        [0, 1, 0],
        [1, 0, 0],
    ])
    >>> y_prob = np.array([
        [0.4, 0.6, 0.3],
        [0.1, 0.2, 0.9],
        [0.9, 0.6, 0.3],
    ])
    >>> recall_at_k(y_true, y_prob, 2)
    0.6666666666666666

2020-10-03 06:00 UTC, AnshumaJain commented on metriks/ranking.py
> +def precision_at_k(y_true: np.ndarray, y_prob: np.ndarray, k: int) -> float:
I did try np.ndarray but it is throwing error, because the function is returning float output.

2020-10-03 06:04 UTC, AnshumaJain commented
Closing this PR to create a new one with the required changes.

2020-10-03 06:04 UTC, AnshumaJain commented
Closing this PR to create a new one with the required changes.

2020-10-03 06:04 UTC, closed without merging